import fs from "fs";
import path from "path";

export function generateImage(prompt = "AIX Image") {
  const outDir = path.join(process.cwd(), "aix-output/images");
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  const fileName = `image_${Date.now()}.txt`;
  const filePath = path.join(outDir, fileName);

  // Demo image proof (text-based)
  fs.writeFileSync(
    filePath,
    `IMAGE GENERATED BY AIX\nPROMPT: ${prompt}\nTIME: ${new Date()}`
  );

  return `/aix-output/images/${fileName}`;
}
