import fs from "fs";
import path from "path";

export function generateVideo(prompt = "AIX Video") {
  const outDir = path.join(process.cwd(), "aix-output/videos");
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

  const fileName = `video_${Date.now()}.txt`;
  const filePath = path.join(outDir, fileName);

  fs.writeFileSync(
    filePath,
    `VIDEO GENERATED BY AIX\nPROMPT: ${prompt}\nTIME: ${new Date()}`
  );

  return `/aix-output/videos/${fileName}`;
}
