import express from "express";
import cors from "cors";
import path from "path";

/* ================= CORE ================= */
import { parseCommand } from "./aix-core/core/command-engine/parseCommand.js";
import { getState, updateState } from "./aix-core/core/state-engine/stateManager.js";
import { createPlan } from "./aix-core/core/planner/planner.js";
import aixRoutes from "./routes/aix.routes.js";

/* ================= INSPECT / FIX ================= */
import { inspectProject } from "./aix-core/inspectors/projectInspector.js";
import { applyFix } from "./aix-core/inspectors/applyFix.js";

/* ================= EXECUTORS ================= */
import { takeScreenshot } from "./aix-core/executors/web/screenshot.js";
import { createFile } from "./aix-core/executors/files/createFile.js";
import { searchKnowledge } from "./aix-core/executors/knowledge/searchKnowledge.js";

/* ================= MEDIA ================= */
import { generateRealImage } from "./aix-core/executors/media/realImageGenerator.js";
import { generateVideo } from "./aix-core/executors/media/videoGenerator.js";

/* ================= APP ================= */
const app = express();
app.use(cors());
app.use(express.json());

app.use("/aix", aixRoutes);

/* serve generated output */
app.use("/aix-output", express.static(path.join(process.cwd(), "aix-output")));

/* ================= HEALTH ================= */
app.get("/", (req, res) => {
  res.send("AIX CORE IS LIVE");
});

/* =====================================================
   MAIN AIX COMMAND ENDPOINT
===================================================== */
app.post("/api/aix", async (req, res) => {
  try {
    const message = req.body.message || "";

    const command = parseCommand(message);
    const plan = createPlan(command);

    /* ========== PROJECT INSPECT ========== */
    if (
      command.goal?.toLowerCase().includes("inspect") ||
      command.goal?.toLowerCase().includes("तपास")
    ) {
      const report = inspectProject(process.cwd());
      updateState("Project inspected");

      return res.json({
        command,
        plan,
        result: report.summary,
        findings: report.findings,
        state: getState()
      });
    }

    /* ========== APPLY FIX ========== */
    if (
      command.goal?.toLowerCase().includes("fix") ||
      command.goal?.toLowerCase().includes("लागू")
    ) {
      const match = command.goal.match(/[A-Z_]+/);
      const fixCode = match ? match[0] : null;

      if (!fixCode) {
        return res.json({
          command,
          plan,
          result: "Fix code सापडला नाही",
          state: getState()
        });
      }

      const fixResult = applyFix(fixCode);
      updateState(`Fix applied: ${fixCode}`);

      return res.json({
        command,
        plan,
        result: fixResult,
        state: getState()
      });
    }

    /* ========== SCREENSHOT ========== */
    if (
      command.goal?.toLowerCase().includes("screenshot") ||
      command.output?.toLowerCase().includes("screenshot")
    ) {
      const targetUrl = command.url || "https://example.com";
      const img = await takeScreenshot(targetUrl);
      updateState("Screenshot taken");

      return res.json({
        command,
        plan,
        result: "Screenshot taken",
        imageUrl: img,
        state: getState()
      });
    }

    /* ========== HTML / FILE CREATE ========== */
    if (
      command.goal?.toLowerCase().includes("html") ||
      command.output?.toLowerCase().includes("html")
    ) {
      const filePath = createFile(
        "demo.html",
        "<h1>Hello from AIX</h1><p>Auto generated HTML</p>"
      );
      updateState("HTML created");

      return res.json({
        command,
        plan,
        result: `HTML created at ${filePath}`,
        state: getState()
      });
    }

    /* ========== KNOWLEDGE ========== */
    if (
      command.goal?.toLowerCase().includes("knowledge") ||
      command.goal?.toLowerCase().includes("माहिती") ||
      command.goal?.toLowerCase().includes("भविष्य") ||
      command.output?.toLowerCase().includes("knowledge")
    ) {
      const data = await searchKnowledge(command.goal);
      updateState("Knowledge searched");

      return res.json({
        command,
        plan,
        result: data.summary,
        sources: data.sources,
        state: getState()
      });
    }

    /* ========== REAL IMAGE GENERATOR ========== */
    if (
      command.output?.toLowerCase().includes("image") ||
      command.goal?.toLowerCase().includes("image") ||
      command.goal?.toLowerCase().includes("इमेज") ||
      command.goal?.toLowerCase().includes("photo")
    ) {
      try {
        const img = await generateRealImage(command.goal);
        updateState("Real image generated");

        return res.json({
          command,
          plan,
          result: "Real image generated by AIX",
          imageUrl: img,
          state: getState()
        });
      } catch (e) {
        return res.json({
          command,
          plan,
          result: "Image generation failed",
          error: e.message,
          state: getState()
        });
      }
    }

    /* ========== VIDEO GENERATOR (DEMO PROOF) ========== */
    if (
      command.output?.toLowerCase().includes("video") ||
      command.goal?.toLowerCase().includes("video") ||
      command.goal?.toLowerCase().includes("व्हिडिओ")
    ) {
      const vid = generateVideo(command.goal);
      updateState("Video generated");

      return res.json({
        command,
        plan,
        result: "Video generated by AIX",
        videoUrl: vid,
        state: getState()
      });
    }

    /* ========== DEFAULT ========== */
    return res.json({
      command,
      plan,
      result: "No execution",
      state: getState()
    });

  } catch (err) {
    console.error("AIX ERROR:", err);
    return res.status(500).json({
      error: "AIX internal error",
      details: err.message
    });
  }
});

/* ================= START ================= */
const PORT = process.env.PORT || 10000;
app.listen(PORT, () => {
  console.log("AIX Backend running on port", PORT);
});
