export default function App(){
  return (
    <div style={{fontFamily:'sans-serif',padding:20}}>
      <h1>boss-app</h1>
      <p>Generated by Boss Aix builder — run npm install and npm run dev</p>
    </div>
  );
}