import fs from "fs/promises";
import path from "path";

function nowStamp() {
  const d = new Date();
  return (
    d.getFullYear() + "-" +
    String(d.getMonth() + 1).padStart(2, "0") + "-" +
    String(d.getDate()).padStart(2, "0") + "-" +
    String(d.getHours()).padStart(2, "0") +
    String(d.getMinutes()).padStart(2, "0") +
    String(d.getSeconds()).padStart(2, "0")
  );
}

export async function buildApp({ name = "boss-app", type = "react-vite" } = {}) {
  const baseDir = path.resolve(process.cwd(), "generated_apps");
  const stamp = nowStamp();

  const folderName = stamp + "-" + name;
  const target = path.join(baseDir, folderName);

  await fs.mkdir(baseDir, { recursive: true });
  await fs.mkdir(target, { recursive: true });

  // package.json
  const pkg = {
    name,
    private: true,
    version: "0.0.1",
    scripts: {
      dev: "vite",
      build: "vite build",
      preview: "vite preview"
    },
    dependencies: {
      react: "^18.2.0",
      "react-dom": "^18.2.0"
    },
    devDependencies: {
      vite: "^4.0.0",
      "@vitejs/plugin-react": "^4.0.0"
    }
  };

  await fs.writeFile(path.join(target, "package.json"), JSON.stringify(pkg, null, 2));

  // index.html
  const indexHtml =
    "<!doctype html>\n" +
    "<html>\n" +
    "<head>\n" +
    "  <meta charset='utf-8'>\n" +
    "  <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n" +
    "  <title>" + name + "</title>\n" +
    "</head>\n" +
    "<body>\n" +
    "  <div id='root'></div>\n" +
    "  <script type='module' src='/src/main.jsx'></script>\n" +
    "</body>\n" +
    "</html>";

  await fs.writeFile(path.join(target, "index.html"), indexHtml);

  // src folder
  await fs.mkdir(path.join(target, "src"), { recursive: true });

  const mainJs =
    "import React from 'react';\n" +
    "import { createRoot } from 'react-dom/client';\n" +
    "import App from './App.jsx';\n" +
    "createRoot(document.getElementById('root')).render(\n" +
    "  React.createElement(React.StrictMode, null, React.createElement(App))\n" +
    ");";

  await fs.writeFile(path.join(target, "src", "main.jsx"), mainJs);

  const appJs =
    "export default function App(){\n" +
    "  return (\n" +
    "    <div style={{fontFamily:'sans-serif',padding:20}}>\n" +
    "      <h1>" + name + "</h1>\n" +
    "      <p>Generated by Boss Aix builder — run npm install and npm run dev</p>\n" +
    "    </div>\n" +
    "  );\n" +
    "}";

  await fs.writeFile(path.join(target, "src", "App.jsx"), appJs);

  const viteConfig =
    "import { defineConfig } from 'vite';\n" +
    "import react from '@vitejs/plugin-react';\n" +
    "export default defineConfig({ plugins: [react()] });";

  await fs.writeFile(path.join(target, "vite.config.js"), viteConfig);

  return {
    ok: true,
    path: target,
    folder: folderName,
    instructions: [
      "cd generated_apps/" + folderName,
      "npm install",
      "npm run dev -- --host"
    ]
  };
}
